spring.application.name=EcopointsP2

spring.data.mongodb.uri=mongodb+srv://<db_user>:<db_password>@brasil.sk6i5.mongodb.net/ecopoints?appName=brasil
spring.data.mongodb.database=ecopoints
server.port=8080